export enum SCORE_ACTION_TYPES {
  SCORE_LIST_DONE = 'SCORE_LIST_DONE',
  SCORE_LIST_FAILED = 'SCORE_LIST_FAILED',
  SCORE_LIST_FETCHING = 'SCORE_LIST_FETCHING',
  SCORE_LIST_INITIAL_FETCHING = 'SCORE_LIST_INITIAL_FETCHING',
}

export enum CLICK_ACTION_TYPES {
  CLICK_DONE = 'CLICK_DONE',
  CLICK_FAILED = 'CLICK_FAILED',
  CLICK_FETCHING = 'CLICK_FETCHING',
}

export enum SESSION_ACTION_TYPES {
  CREATE_SESSION = 'CREATE_SESSION',
}
